### ISSUE TITLE
为什么我的visual studio没有办法添加依赖？

### ISSUE THREAD

**Issue by huoshuigege** [H4rry217/ar-example-plugin#2]
![image](https://github.com/H4rry217/ar-example-plugin/assets/107799621/8edf2d6b-88e5-4fca-8f94-32b682e48464)
为什么我的visual studio没有办法添加依赖？作者能帮忙看看吗  第一次使用这个编辑器

**Comment by H4rry217** [comment]
请附带具体的操作步骤（截图最好）和VS版本

**Comment by huoshuigege** [comment]
我的版本为vs 2022
![image](https://github.com/H4rry217/ar-example-plugin/assets/107799621/3c88cec3-5cd2-4651-8509-42ff4458e2e2)
步骤1：启动vs,并创建新的项目
![image](https://github.com/H4rry217/ar-example-plugin/assets/107799621/ac2131fe-26b2-4036-8245-923953f2ea3f)
步骤2：选择C#的类库
![image](https://github.com/H4rry217/ar-example-plugin/assets/107799621/d752f305-a321-4db3-b47a-c8d82228400f)
步骤3：创建项目，并选择 .net6.0
![image](https://github.com/H4rry217/ar-example-plugin/assets/107799621/9cbd20ba-476b-445d-8163-3c1f77382b2a)
![image](https://github.com/H4rry217/ar-example-plugin/assets/107799621/9783dc5a-4098-4f50-976f-93fa38e8ead7)
步骤4：项目创建完成，但没有依赖可以进行添加
![image](https://github.com/H4rry217/ar-example-plugin/assets/107799621/724bf865-10e8-4581-b82a-f2edea413ed9)
